### ISSUE TITLE
Doesn't Work Anymore?

### ISSUE THREAD

**Issue by ghost** [IRDeNial/discord-hide-channel-list#10]
Perhaps the recent client updates broke something, but copying and pasting main.js into the developer console after enabling Developer Mode doesn't actually do anything. It reports back with this error as below.

`Uncaught TypeError: Cannot read property 'insertBefore' of null`
    `at Object.addToolbarItem (<anonymous>:11:58)`
    `at <anonymous>:37:21`
    `at <anonymous>:39:3`

**Comment by notmike101** [comment]
Now working thanks to pull request #11
