### ISSUE TITLE
Instead of channels, enable collapse of Guilds

### ISSUE THREAD

**Issue by ghost** [IRDeNial/discord-hide-channel-list#8]
Could this feature be added? What modifications would it need for me to do this? Thanks!

**Comment by notmike101** [comment]
I'm not sure I understand what you're asking?

**Comment by ghost** [comment]
Instead of making the channel list collapsible, could you make it collapse the servers (aka "guilds")?

**Comment by notmike101** [comment]
Sorry for the late reply.  That's outside of the scope of this plugin.

Closing.
