### ISSUE TITLE
collapse/hide chat area?

### ISSUE THREAD

**Issue by tylerstraub** [IRDeNial/discord-hide-channel-list#9]
Would it be possible to add another button to collapse or completely hide the entire chat area of Discord? 

My buddy who streams often only really needs to see and interact with the voice chat area of Discord and the discord window occupies a ton of horizontal space on the monitor. 

Is the horizontal window minimum value even an attribute we could even control using a discord plugin?

**Comment by notmike101** [comment]
Would be good for a separate plugin, not this one.

Go ahead and fork this repository and make it do that.
